---
- name: configure load balancer
  hosts: balancers
  vars:
    haproxy_backend_servers:
      - name: app1
        address: servera.lab.example.com:80
      - name: app2
        address: serverb.lab.example.com:80
  roles:
    - balancer
  post_tasks:
    - name: Configure firewall
      firewalld:
        service: http
        state: enabled
        permanent: yes
        immediate: yes

- name: Cofigure phpinfo
  hosts: webservers
  roles:
    - phpinfo
  post_tasks:
    - name: Copy hello.php file
      template:
        src: hello.php
        dest: /var/www/html/hello.php
      notify:
        - restart webserver
  
...
