---
- name: Generate hardware report
  hosts: all
  tasks:
    - name: Download hwrepot.empty 
      get_url:
        url: http://content.example.com/courses/rh294/rhel8.0/materials/hwreport.empty
        dest: /root/hwreport.txt
      ignore_errors: yes
    - name: Copy hwreport.empty file
      copy:
        src: hwreport.empty
        dest: /root/hwreport.txt
    - name: get hostname
      replace:
        path: /root/hwreport.txt
        regexp: "inventoryhostname"
        replace: "{{ ansible_hostname }}"
    - name: get total memory
      replace:
        path: /root/hwreport.txt
        regexp: "memory_in_MB"
        replace: "{{ ansible_memtotal_mb | default ('NONE') }}"
    - name: get BIOS version
      replace:
        path: /root/hwreport.txt
        regexp: "BIOS_version"
        replace: "{{ ansible_bios_version }}"
    - name: SDA disk size
      replace:
        path: /root/hwreport.txt
        regexp: "disk_vda_size"
        replace: "{{ ansible_devices.sda.size | default ('NONE') }}"
    - name: SDB disk size
      replace:
        path: /root/hwreport.txt
        regexp: "disk_vdb_size"
        replace: "{{ ansible_devices.sdb.size | default ('NONE') }}"
...
