---
- name: Create a Web content directory
  hosts: dev
  tasks:
    - name: Create webdev user
      user:
        name: webdev
        state: present
    - name: Install httpd and firewalld 
      yum:
        name: 
          - httpd
          - firewalld
        state: present
    - name: Started and Enabled httpd and firewalld
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd
        - firewalld
    - name: Allow http in the firewalld
      firewalld:
        service: http
        state: enabled
        permanent: yes
        immediate: yes
    - name: Create /webdev directory
      file:
        path: /webdev
        group: webdev
        mode: 2775
        state: directory
        setype: httpd_sys_content_t
    - name: crate symbolic link
      file:
        src: /webdev
        dest: /var/www/html/webdev
        state: link
    - name: Copy index.html file
      copy:
        content: "Development"
        dest: /webdev/index.html
        setype: httpd_sys_content_t 
...
