version: 0.2

env:
  parameter-store:
     DOCKER_USERNAME: /flask-app/docker-credentials/username
     DOCKER_PASSWORD: /flask-app/docker-credentials/password
     DOCKER_URL: /flask-app/docker-registry/url
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  install:
    runtime-versions:
      python: 3.11
      # name: version
    #commands:
      # - command
      # - command
  pre_build:
    commands:
      - pip install -r requirements.txt
      # - command
  build:
    commands:
      - echo "Building Docker Image"
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_URL"
      - docker build -t "$DOCKER_URL/$DOCKER_USERNAME/flask-app:latest" .
      - docker push "$DOCKER_URL/$DOCKER_USERNAME/flask-app:latest"
  post_build:
    commands:
      - echo "Build is successful"
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
