---
# tasks file for apache
- name: Install httpd package
  yum:
    name: httpd
    state: present
- name: Enabled httpd service
  service:
    name: httpd
    state: started
    enabled: yes
- name: Enabled http service
  firewalld:
    service: http
    state: enabled
    permanent: yes
    immediate: yes
- name: Copy template file index.html.j2
  template:
    src: index.html.j2
    dest: /var/www/html/index.html 
