version: '1.0'
services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: docker/dockerfiles/php.dockerfile
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:5.7
    env_file:
      - ./docker/env/mysql.env
  composer:
    build:
      context: .
      dockerfile: docker/dockerfiles/composer.dockerfile
    volumes:
      - ./:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: docker/dockerfiles/php.dockerfile
    volumes:
      - ./:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
