version: "3"
services:
  dns:
    image: sameersbn/bind:9.9.5-20170129
    container_name: dns
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 10000:10000
    environment:
      - ROOT_PASSWORD=secretpassword
    volumes: 
      - dns-data:/data
     # - /resolv/resolv.conf:/etc/resolv.conf
    networks:
      - frontend-net
networks:
  frontend-net:
    name: frontend-net
    external: true
volumes:
  dns-data:
    external: true
