---
- name: This is ti ready App Server
  hosts: appnode
  tasks:
    - name: Install apache
      yum:
        name: httpd
        state: present
    - name: Start apache service
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Enable http in firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled
    - name: Install PHP repo
      yum:
        name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: latest
    - name: Enable PHP 7.2
      shell: yum-config-manager --enable remi-php72
    - name: Install PHP
      yum:
        name: php
        state: present
    - name: Install php-pdo
      yum:
        name: php-pdo
        state: present
    - name: Install php-pdo_mysql
      yum:
        name: php-pdo_mysql
        state: present
    - replace:
        path: "/etc/httpd/conf/httpd.conf"
        regexp: "AllowOverride None"
        replace: "AllowOverride ALL"
    - name: Restart the MySQL service
      service:
        name: httpd
        state: restarted

...
